services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "g:/data-engineering-zoomcamp/data-engineering-zoomcamp/01-docker-terraform/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "10090:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "10091:80"
